### PR TITLE
don't use repository.liveramp.com at all

### PR DESCRIPTION
**Pull request by joshk0**

### CODE REVIEW

**Comment by aharelick** [comment]
what's the context here?

**Comment by joshk0** [comment]
Good question. For a while, I have been moving OSS dependencies to publish to Sonatype Nexus (see [this thread](https://liveramp.slack.com/archives/C3TUTRT35/p1554495559207200) and also [this thread](https://liveramp.slack.com/archives/C2CG170J0/p1556580283221600) and also [this doc](https://github.com/LiveRamp/team_devops/tree/master/util/git) .)

The reason for doing this is that BDI currently operates repository.liveramp.com which is a bare EC2 instance with an external IP which serves all our OSS artifacts. It's part of the source repos that library.liveramp.net can source from, as is sonatype.

To avoid having to migrate repository.liveramp.com to GCP, as well as mitigating a notable security risk (that being said this instance isn't in any of the VPCs peered to colo), the goal is to publish all OSS artifacts to Sonatype and eradicate repository.liveramp.com entirely.

Let me know if this clears it up, happy to answer any more questions, and sorry for the delay as I've been on PTO for the past week.

**Comment by joshk0** [comment]
Sure, the goal is to move all our OSS artifacts to Sonatype Nexus to avoid needing to maintain repository.liveramp.com . After no-one is using repository.liveramp.com, we can kill it!

**Review by aharelick — APPROVED** [review]
👍

**Pull request merged**
